class Strings {
  static const String APP_NAME = "CoinPedia";

  static const List<String> COIN_ADLARI = [
    "Bitcoin",
    "Etherium",
    "BinanceCoin",
    "DogeCoin",
    "Ripple",
    "Cardano",
    "ChainLink",
    "Neo",
    "Stellar",
    "Tron",
    "Bittorrent",
  ];

  static const List<String> COIN_FIYAT = [
    "55,256.65 Dolar",
    "2,700.41 Dolar",
    "600.45 Dolar",
    "0.2845 Dolar",
    "1.52 Dolar",
    "1.45 Dolar",
    "40.21 Dolar",
    "100.48 Dolar",
    "0.62 Dolar",
    "0.15 Dolar",
    "0.0077 Dolar",
  ];

  static const List<String> COIN_AYRINTI = [
    "\tBitcoin Tarihçesi Ve Özellikleri\n\n"
        "\t2008 krizi sonrası Satoshi Nakamato adlı kişi ya da kişiler uçtan uca elektronik ödeme sistemi olan Bitcoin'e dair teknik yazılarını yayınladılar. Böylece Bitcoin merkezsizleştirilmiş, üçüncül müdahalelere karşı korumalı kripto para birimi olarak ortaya çıktı. 2009 yılında halka açık ağ olarak kullanıma girdi. Sonrasında Bitcoin, ilk başarılı kripto para olarak 1. nesil blockchain olarak adlandırıldı.Dağıtık yapısı sayesinde çok kısa bir sürede günümüz finansal düzenine karşı yükselişe geçti. Bitcoin ağına giren işlemlerin takip edilmesi mümkün iken, işlemi gerçekleştiren kişinin kim olduğunu bulmak olanaksızdır. Bitcoin Blockchain ağında onaylanan işlemler, zincir yapısından dolayı geri döndürülemez ve bu işlemler değiştirilemez.Düzenlemeye ya da kontrole tabii tutulamadığı için Bitcoin'in değeri sıfır noktasından, binlerce dolara kadar yükselmiştir. Bitcoin'in yükselişinin ardından birçok kripto para birimi daha ortaya çıkmıştır. Bu para birimlerine alternative coin, bir diğer değişle alt coin denmektedir. Alternatif kripto para birimleri yaratılırken çeşitli noktalarda farklı özelliklere sahip olarak rekabet avantajından yararlanılmış ve yeni market tipleri ortaya çıkmıştır. Bu farklılıklara üretilebilecek maksimum para miktarı, algoritma, blockchain alt türleri (özel/paylaşımlı, izinli/izinsiz mutabakat) örnek olarak verilebilir.Bitcoin blockchain platformunda üretilebilecek maksimum Bitcoin miktarı 21 milyon adettir. Bitcoin uçtan uca, adresten adrese transfer imkanı sağlamaktadır, ayrıca blok üretim süresi yaklaşık 10 dakikadır.Bitcoin adresleri kullanıcıların platform üzerindeki kimlikleridir. İşlemi yapan şahısla ilişkilendirilemezler ve bu adreslerin anahtarları kaybedildiğinde adresler üzerinde hak iddia edilemez.\n\n"
        "\tBitcoin’in Avantajları Nelerdir?\n\n"
        "\tBitcoin kullanımının çeşitli risklerinin yanı sıra pek çok avantajı da vardır. Enflasyon ve çökme riskinin düşük olması, basit, güvenilir ve iz sürülemez* (anonim) olması en temel avantajlarındandır. Para transferlerinin geleneksel yöntemlere kıyasla daha güvenli, daha ucuz ve daha hızlı olması Bitcoin’in sağladığı önemli bir avantajdır. Milyonlarca lira değerindeki Bticoinlerinize cüzdan erişimi sağlayabildiğiniz her yerden ulaşabilirsiniz.Bu denli yüksek miktarlarda paraları nakit veya farklı bir yöntemle bu kadar kolay taşımanın yolu yoktur. Yapılan işlemlerin ve hesap bakiyenizin herhangi bir kişi/kişiler veya devlet ve banka tarafından bilinmemesi ve kontrol edilememesi de bazı avantajlar sağlamaktadır.\n\n"
        "\tBitcoin’in Dezavantajları Nelerdir?\n\n"
        "\tİzinin sürülememesi bazı durumlarda avantaj sağlasada dezavantaj oluşturduğu durumlarda mevcuttur. Ticaretinin illegal olduğu ürünlerin ödemelerinde kullanılmasına ve kara para aklama maksadıyla kullanılmasına neden olmaktadır. Bu teknoloji üzerinde uzmanlaşmış kişi sayısının az olması, kaybetme riski, harcama yapılabilecek platformların darlığı sistemin diğer dezavantajlarındandır.\n\n"
        "\tBitcoin’in Kaynağı Nedir?\n\n"
        "\tBitcoin herhangi bir devlete veya merkez bankasına bağlı değildir. Geleneksel paralarda olduğu gibi karşılığında altın gibi herhangi bir değerli maden yoktur. Fiziksel olarak basılan bir para değeri değilidir. Bitcoin tamamen sanal olarak üretilen ve temelinde matematik formülü olan bir sistemdir. Bu matematik formülü herkese açıktır ve isteyen herkes bu sisteme dahil olabilir. Bitcoin madenci sistemine dahil olan her birey sistemin güvenliğini sağlamlaştırmış olur.\n\n"
        "\tBitcoin Madenciliği\n\n"
        "\tBitcoin üretiminin sağlanması ve blok zincir sisteminin sürekliliğini ve güvenliğini tesis edilebilmesi için gerekli bir sistemdir.Başlangıçtan bu yana bir çok farklı cihazla yapılan madencilik, artan rekabet ortamı nedeniyle sürekli olarak bu alanda daha fazla kar getirecek yeniliklerin doğmasına neden olmuştur.Madencilik esasında kriptografi şifreleri çözerek sisteme yeni blokların eklenmesidir. Şifrelerin çözülmesi, bilgisayarın işlemci kapasitesine ve şifrenin uzunluğuna bağlıdır. Şifreleri çözülmesi ile oluşturulan bloklar üzerinden madenciler Bitcoin ile ödüllendirilir.Madenci sayısının artması ve sistemin yalnızca 10 dakika içerisinde bir blok üretimine izin vermesi, madenciliği kar edilmesi zor bir duruma sokmuştur. Ayrıca, Bitcoin adedinin sınırlandırılmış olması da madenciliği olumsuz etkileyen bir etken olsa da Bitcoin para biriminde enflasyonun oluşmasını engellemektedir.\n\n",
    "\tEthereum ilk olarak Kuzey Amerika Bitcoin Konferansında, Ethereum kurucusu Vitalik Buterin tarafından tanıtımı yapılan bir sistemdir. Genel olarak bir alt coin statüsünde görülse de Ethereum esasında blockchain teknolojisinin gelişmesini ve daha fazla alanda kullanılmasını amaçlayan bir yenilikçi bir sistemdir.Ethereum kısaca, güç kaynağı olarak Ether (ETH) kripto para birimini alan bir Kripto İşletim Sistemidir. Amaç Bitcoin’inde bağlı olduğu blockchain sistemi üzerinde kullanıcıların bu sistem üzerinden yeni yazılımları oluşturmasını sağlamaktadır. Ethereum’un kullanıcılara sağladığı bu özgürlük sayesinde bir çok alt coin çıkarılmasına olanak sağlar.Ethereum sistemi ile amaçlanan, kişisel veriler gibi bilgilerin üçüncü şahıslar tarafından depolanmasını ve farklı amaçlar için kullanılmasını engellenmesidir. Bugün neredeyse internetten yaptığımız bütün işlemler (alışveriş, banka işlemleri, sosyal medya kullanımımız, internet geçmişimiz vb.) veriler halinde data banklarda kayıt altına alınmaktadır. Bu bilgilerin hangi amaçlar doğrultusunda kullanılacağı konusu ise tam bir bilinmezliktir.Ethereum sistemi ile bu işlemler tamamen dağınık ve anonim bir şekilde bir çok farklı cihaz üzerinde saklanmaktadır. Böylece bu bilgilere erişim imkansız bir hale gelir ve bütün bir interneti merkezsiz bir platforma çevirir.Bu merkezsiz sisteme dahil olacak yazılımların üretilebilmesi için Ehereum, Ether kripto para birimini bir yönüyle bir yakıt olarak kullanılmasını amaçlar.\n\n"
        "\tEthereum ve Bitcoin Arasındaki Farklar Nelerdir?\n\n"
        "\t*Bitcoin sistemi ile yapabileceğeniz işlemler belli iken, Ethereum sistemi ile çok farklı yazılımlar ile yeni sistemler ve yeni alt coinler üretebilirsiniz.\n\n"
        "\t*Ethereum sistemi, Bitcoin blockchain sistemine göre daha yenilikçi bir sistemdir.\n\n"
        "\t*Bitcoin madenciliğinde işlemci gücünüze göre kazanç sağlarken, Ethereum madenciliğinde üreticiler arasında denge gözetilmektedir.\n\n"
        "\t*Bitcoin sisteminde bir blokun oluşması 10 dakika sürmektedir. Ethereum sistemin de bir blokun oluşma süresi 15 saniye olduğundan onaylama süresi çok daha kısadır.\n\n"
        "\tEthereum Madencilği Nasıl Yapılır?\n\n"
        "\tMadencilik aynı Bitcoin mantığı ile bu sistemin süreklilik ve güvenliği için önemli bir faktördür. Ethereum madenciliğinin herkes tarafından yapılabilmesi için sistem gereksinimi Bitcoin madenciliğindeki gibi özel üretim cihazlar ile değil ekran kartı (GPU) ile yapılmaktadır. Madenci sayısının artması, Ethereum madenciliğinde de günden güne kazancın azalmasına neden olmaktadır.\n\n",
    "\tBinance Coin Tarihçesi Ve Özellikleri\n\n"
        "\tBinance Coin (BNB), Binance kripto para değişim borsasının çıkardığı bir kripto para birimidir. Binance Coin (BNB) ERC-20 tabanlı bir kripto para birimi olarak çıkarılmıştır, fakat daha sonra Binance kendi zincirini kurmuş ve BEP2 tabanlı bir alt yapıya geçmiştir. Mevcut ERC20 tokenlar yakılarak BEP2 tokenları haline getirilmektedir.Hacmi ile dünyanın en büyük borsalarından olan Binance, borsa hacmi ile orantılı olarak Binance Coin (BNB) kripto para biriminin de hacmi ve reel para karşısındaki değeri ciddi bir yükseliş göstermiştir.\n\n"
        "\tBinance Coin (BNB) Nasıl Çalışmaktadır?\n\n"
        "\tPiyasada toplam 155,536,713 BNB bulunmaktadır. Binance borsası yıllık karının % 20’si ile Binance Coin (BNB) satın almaktadır ve aldığı BNB coinleri yakmaktadır. Bu işlem piyasada 100.000.000 BNB kalana devam edecektir. Bu işlem ile amaç Binance Coin (BNB) piyasasında enflasyonu engellemeyi amaçlamaktadır. Binance son whitepaper güncellemesi ile karının %20'si ile BNB alacakları maddesini, karının bir kısmı ile alacakları şeklinde değiştirmiştir.Binance Coin (BNB) ile Binance borsasında kripto para birimleri arasında alış/satış yapılabilmektedir.Binance Coin (BNB) ile Binance borsasında alış/satış işlemlerinde alınan komisyon ödenebilmektedir. Binance Coin (BNB) ile yapılan ödemelerde Binance birinci sene %50, ikinci sene %25, üçüncü sene %12,5 ve dördüncü sene %6,75 oranında komisyon oranlarında indirim sağlamaktadır. Seviyeler kullanıcının elinde bulundurduğu BNB miktarı ve yapmış olduğu toplam hacime göre verilmektedir.\n\n"
        "\tBinance Coin (BNB) Madenciliği Nasıl Yapılır?\n\n"
        "\tBinance Coin (BNB) madenciliği yapılmayan bir kripto para türüdür. Tüm Binance Coin (BNB) miktarı Binance borsası tarafından ilk gün üretilmiş, yarısı halka satılmıştır.\n\n",
    "\tDogeCoin Tarihçesi ve Özellikleri\n\n"
        "\tSon dönemlerde adı sıklıkla duyulan kripto paralardan biri olan Dogecoin (DOGE) 2013 yılının Aralık ayında ortaya çıkmıştır. Günümüzde yatırım ve işlem amaçlı kripto paraların daha fazla tercih edilmesi sebebiyle Dogecoin (DOGE) ve türevleri dijital paralar gündemde yer tutmaktadır.Geleneksel bankacılık işlem ücretlerinin olmadığı ve aynı zamanda eğlenceli bir ödeme sistemi oluşturmak amacıyla tasarlanan Dogecoin (DOGE) Jackson Palmer ve Billy Markus tarafından üretilmiştir. Ocak 2014 tarihine gelindiğinde bu para birimi ulaştığı toplam işlem hacmi ile Bitcoin de dahil olmak üzere çok sayıda kripto para birimini geride bırakmıştır. Yaşanan bu Dogecoin (DOGE) yükselişi devam etmiş, 7 Ocak 2018 tarihinde 0,017 dolar zirvesine erişmiştir.Dogecoin (DOGE), blockchain teknolojisinde bir yenilik çıkarma amacı olmadığı için transferleri, Litecoin kripto para biriminin kurduğu blockchain ağı üzerinden gerçekleştirilmektedir. Litecoin ağında yapılan güncellemeler Dogecoin (DOGE) ağı için de geçerlidir.İlk ortaya çıktığında Dogecoin (DOGE) yatırım amacıyla her bir blok madenciliği için kullanıcıya rastgele bir ödül verilmekte iken ilerleyen zamanlarda bu ödül statik hale dönüştürülmüştür.İsmini ünlü bir internet karakterinden alan Dogecoin (DOGE) daha erişilebilir ve dost canlısı bir kripto para olması amacıyla tasarlanmıştır. Bu sayede Bitcoin’in karmaşıklığından kaçan kullanıcılara erişimini mümkün olacağı düşünülmüştür.Dogecoin (DOGE) piyasası açısından bakıldığında bu para birimi en aktif ve en büyük topluluklardan birine sahip olmasıyla bilinir. Özellikle bahşiş hizmeti için yaygın olarak kullanılan bu kripto para çeşitli projeleri finanse etmek amacıyla da tercih edilmektedir. Bahşiş amaçlı kullanım şeklinde kullanıcılar tanınması gerektiğine inandıkları katkılar ya da göndericiler için diğer kullanıcıya bahşiş vermektedir. Bunun etkili olduğu ifade edilmektedir.Dogecoin (DOGE)’i diğer kripto para birimlerinden ayıran en önemli özellik deflasyonist değil enflasyonist olmasıdır. Yani dolaşımdaki Dogecoin (DOGE) ile ilgili herhangi bir sınırlama yoktur. Bitcoin ve benzeri para birimleri sınıra ulaştığında madenciliğe devam etmek bir süre sonra karlı hale gelmeyecektir. Bu nedenle Dogecoin (DOGE) uzun vade işlemleri açısından da avantajlıdır.\n\n"
        "\tDogecoin (DOGE) Madenciliği Nasıl Yapılır?\n\n"
        "\tDogecoin (DOGE) satın alma fikrine sahip olan kişiler için genellikle ilk adım Dogecoin (DOGE) madenciliği olacaktır. En basit şekliyle bakıldığında bu işlem Dogecoin (DOGE) blockchain’inde işlemlerin onaylanması sonucunda yeni Dogecoin (DOGE) ile ödüllendirilmektedir. Ancak bu onay için karmaşık matematiksel denklemlerin çözülmesi gerekir ve bu amaçla güçlü özelliklere sahip donanımlı bilgisayarlar tercih edilir.Dogecoin (DOGE) madenciliği yapılırken blok süresi, zorluk seviyesi, algoritma ve ödül yönlerinden diğer kripto para birimlerine kıyasla farklılıklar vardır. Örneğin Dogecoin (DOGE) için dakika başına blok süresi 1 iken bu süre Bitcoin için 10 dakika, Litecoin için ise 2,5 dakika olarak ifade edilir. Yani Dogecoin (DOGE) madenciliği yapmak diğerlerine göre daha hızlıdır.Madencilik yapmak için kullanıcılara solo ve madencilik havuzu olmak üzere iki farklı seçenek sunulur. Soloda işlemleri kişi kendi başına yapar. Havuz mantığında ise işlemleri onaylatıp ödül kazanmayı amaçlayan ve işlem güçlerini paylaşarak artıran bir grup kullanıcı yer almaktadır. Eğer havuz kapsamında madencilik yapılırsa bunun için bir ücret ödemek gerekecektir. Ayrıca ödül alındığında bunun bir kısmı kişiye kalacaktır.Solo madencilik yaparken ise bekleme süresi uzun olup risk biraz daha yüksektir. Yani ilk blok ödülü alabilmek için beklenmesi gereken süre haftalar ya da aylar olabilir. Fakat bir ödül kazanıldığında bir paylaşım olmaz ve bunun tamamı kullanıcıya kalır. Bu sayede ücret ödemeye de gerek kalmayacaktır. Elde edilecek kazanç belirlenirken ise o an geçerli olan Dogecoin (DOGE) TL fiyatı geçerli olacaktır.\n\n",
    "\tRipple Tarihçesi Ve Özellikleri\n\n"
        "\tRipple, 2012 yılında ortaya çıkmış bir ödeme ağı sistemi (RippleNet) ve kripto para değeridir (XRP). Ripple diğer birçok kripto para birimlerinin aksine merkezi olan bir kripto para birimidir. Blockchain sistemi üzerinde işlem görmesine rağmen işlem gören bütün defterler şirket tarafından yönetilmektedir.Ripple ile amaç büyük miktarlardaki varlık ve para transferlerinin hızlı, güvenilir ve ucuz bir şekilde, blockchain sistemi üzerinden yapılmasıdır.Ripple şirketinin CEO’luğunu Brad Garlinghouse yürütmektedir ve dünyanın birçok yerinde ofisleri bulunmaktadır.Ripple şu anda kripto para değerleri arasında Bitcoin ve Ethereum’dan sonra üçüncü en çok piyasa değeri olan kripto pardır.Kurumsal bir merkeze sahip olması Ripple kripto para değerinin, ödeme sistemleri sağlayıcısı şirketlerin ve bankaların tercih ettiği bir kripto para ve transfer sistemi olmasını sağlamıştır.\n\n"
        "\tRipple’ın Avantajları Nelerdir?\n\n"
        "\t*Ripple, varlık ve para transferlerinde blockchain teknolojisi sayesinde çok düşük maliyetlere ve çok kısa sürelerde uluslararası gönderim imkanı sunmaktadır.\n\n"
        "\t* Piyasa değerinin en yüksek üçüncü kripto para olması ve çok yüksek işlem hacmine sahip olması birçok borsada işlem görmesine neden olmaktadır. Bu durum da erişilebilirliği kolaylaştırmaktadır.\n\n"
        "\t*Bitcoin gibi merkezi olmayan kripto para değerlerinin aksine, değerinin kar eden bir şirkete dayandırılıyor olması Ripple’ı diğer kripto para değerlerinden ayıran en önemli unsurdur.\n\n"
        "\t* Büyük ödeme sistemleri sağlayıcı şirketler ve bankalarla yaptığı anlaşmalar ile günden güne değerini arttırmaya devam etmektedir.\n\n"
        "\tRipple Madenciliği Nasıl Yapılır?\n\n"
        "\tRipple’ın, diğer kripto para birimlerinin aksine madenciliği veya üretimi yapılmamaktadır. Dolaşımdaki bütün Ripple değerlerini şirket üretmektedir. Toplam üretilen Ripple miktarı 100 milyar adet olsa da, şirket piyasaya sadece 40 milyar adet Ripple sunulmuştur.Bitcoin ve diğer kripto para birimlerinden farklı bir politika izleyen şirket madencilikten farklı bir üretim sistemi benimsemiştir. Üretilen Ripple’lar belli aralıklarla piyasaya sürülmeye devam etmektedir.\n\n"
        "\tRipple ile Bitcoin Arasındaki Farklar Nelerdir?\n\n"
        "\t* Bitcoin sistemi herhangi bir merkeze bağlı değildir, Ripple ise bir şirket bünyesindedir ve denetlenmektedir.\n\n"
        "\t*Bitcoin transfer işlemlerinde her bir saniyede 4 işlem yapabilirken, Ripple’da bir saniyede 1500 işlem yapılabilmektedir. (Bu rakamlar zamanla değişebilir)\n\n"
        "\t*Transfer işlemleri için kesilen komisyon ücretleri konusunda Ripple, Bitcoin’den çok daha uygun bir yöntemdir.\n\n"
        "\tBaşarılı olacağınız meslekler: Askerlik, doktorluk, yöneticilik\n\n"
        "\tBurcunuzdan olan ünlüler: Uğur Mumcu, Gönül Yazar, Neil Armstrong, Benito Mussolini, Fidel Castro, Henry Ford, Madonna\n\n",
    "\tCardano(ADA) Tarihçesi ve Özellikleri\n\n"
        "\tCardano, kripto para göndermek ve almak için kullanılabilecek ADA kripto sistemine sahip bir platformdur. Bu kripto para, paranın geleceğini temsil eder ve kriptografi ile güvenli olması garanti edilen hızlı, doğrudan transferleri mümkün kılar.Cardano yalnızca bir kripto para birimi değildir, her gün dünyadaki bireyler, kuruluşlar ve hükümetler tarafından kullanılan finansal uygulamaları yürütebilecek teknolojik bir platformdur. Platform, sistemde daha kolay güncelleme yapabilme ve yumuşak çatallanmalarla yükseltme yapılabilmesini kolaylaştıracak bloklar halinde inşa edilmiştir. ADA’yı yönetecek olan temel katmanının tamamlanmasının ardından, akıllı sözleşmeleri, ileride yapılacak ticaret ve işleri destekleyecek dijital yasal anlaşmaları ele almak için ayrı bir hesaplama katmanı yaratılacaktır. Cardano, herhangi bir merkezi olmayan fakat bunun yerine bir blok zincir üzerinde çalışan merkezi olmayan uygulamaları veya dapps (kullanıcıları ve tedarikçileri direkt olarak birbirine bağlayan sistem) hizmetlerini de yürütecektir.Cardano’nun sunduğu yenilik, kullanıcıların ihtiyaçlarını düzenleyicilerin talepleriyle dengeleyecek ve mahremiyeti düzenleme ile birleştirecek şekilde olmasıdır. Cardano’nun vizyonu, yeni düzenlenmiş bilgi işlem tarzının, herkese adil finansal hizmetlere açık erişim sağlayarak daha fazla finansal katılımı sağlayacağıdır.\n\n"
        "\tCardano’nun kurucusu Charles Hoskinson’dur. Blockchain geliştiricisi ve Blockchain’de birden fazla kilit projede ortak kuruculuk yapan isimlerin başında gelmektedir. Charles, Cardano’nun yanı sıra, Ethereum ve Ethereum Classic’in de kurucuları arasındadır.Charles Hoskinson 2013 yılında, EOSIO‘nun kurucu ortağı Dan Larimer ile birlikte, ilk blok zinciri ve kripto para birimi başlangıcı olan Invictus Innovations’ı başlattı\n\n"
        "\tCardano ve Diğer Kripto Paralar Arasındaki Fark Nedir?\n\n"
        "\tCardano fiyatlarının artacağı yönündeki olumlu tahminlerin bir çoğu sunduğu teknik bazlı nedenlerden dolayıdır. Bunlardan biri kripto para biriminin blok oluşturma algoritmasıdır.Bununla birlikte, Alternatif Alım Kanıtı algoritması, kripto para madenciliğinin elektrik tüketimini azaltmanın bir yolu olarak önem kazanıyor. Cardano’nun Ouroboros protokolü, ilk Stake of Proof sistemlerinden biriydi ve şimdiye kadar kanıtlanmış olan güvenlik sistemiydi. Kullanıcı güvenliği için isteklerini geliştirerek Daedalus Cüzdanı’nın geliştirilmesine başladılar. Bir kripto para cüzdanının normal gizlilik hususlarına ek olarak, Daedalus ayrıca belirli harcama şifrelerini ve işlem izlemesinin de özelleştirilmesini sağlar.\n\n"
        "\tCardano (ADA) Madenciliği Nasıl Yapılır?\n\n"
        "\tCardano (ADA) madenciliği, diğer kripto para birimlerinden alışık olduğumuz sistem ile yapılmamaktadır. Bitcoin madenciliğinde olduğu gibi özel bir cihazla elektrik tüketimi ile bir madencilik yapılamamaktadır.Cardano madenciliği sistemi şu şekilde çalışmaktadır, bu işlem için uygun olan Cardano cüzdanınıza bir miktar Cardano bakiyesi yüklüyorsunuz ve bu bakiyeniz oranında belli bir yüzde ile size Cardano kazandırıyor. Bu sistem Proof of Stake yöntemi ile yapılmaktadır.Cardano madenciliği için özel bir madenci cihazı ya da elektrik tüketimine gerek bulunmamaktadır. Cardano cüzdanınızda bulunan bakiyeniz oranında Cardano ödülü alıyorsunuz ve böylece sistem diğer madencilik türlerine göre daha pratik bir madencilik ile işlemlerine hız kesmeden devam edebiliyor.\n\n",
    "\tChainLink(LINK) Tarihçesi ve Özellikleri\n\n"
        "\tSan Francisco şehrinde bulunan finansal teknoloji şirketi SmartContract Haziran 2017'de Chainlink kısaltması LINK olan Ethereum blockchain'i ERC-20 tabanlı Chainlink'i başlattı.Geliştiricileri tarafından akıllı sözleşmelerin veri akışları, web API'leri ve geleneksel banka hesap ödemeleri gibi zincir dışı kaynaklara erişmesine izin vererek akıllı sözleşmeler ile blockchain arasındaki bağlantıyı sağlamayı amaçlayan güvenli bir blockchain aracı olarak tanımlanmaktadır.Chainlink (LINK) geliştiricileri, akıllı sözleşmelerin geleneksel yasal anlaşmalara duyulan ihtiyacı değiştirerek birçok endüstride önemli ölçüde değişim yapabilmiş olmasına rağmen, blockchain teknolojisi ile ilgili temel fikir birliği protokollerinin akıllı sözleşmelerin diğer geleneksel sistemler ile etkin bir iletişim kurulamadığına inandıkları için blockchain dışı sistemler ile bir köprü vazifesi görmek istediklerini belirtiyor.Chainlink ekosistemi, LINK token ve LINK ağı etrafında şekillenir. API'ler ve diğer platformların piyasaya sürülmesiyle, geliştiriciler iş dünyasında akıllı sözleşmelerin uygulanabilirliğini ve kullanılabilirliğini artırmayı amaçlamaktadır.Chainlink ağı, bir veri beslemesi olan veya başka bir API'ye sahip olan kişilerin, Chainlink belirteçleri karşılığında, doğrudan akıllı sözleşmelere sunmalarına olanak sağlayacaktır. Bu tür kişiler, API tabanlı hizmetlerini doğrudan LINK tokeni karşılığında akıllı bir sözleşmeye ve blockchain sistemine entegre eder.\n\n"
        "\tChainlink (LINK) Avantajı Nedir?\n\n"
        "\tChainlink sistemi, blockchain dışı sistemlerin akıllı sözleşmeler vasıtasıyla blockchain sistemlerine entegre olmasını sağlamaktadır. API tabanlı sunulan hizmetlerin blockchain sistemlerinin entegre olması, işlem güvenliği, 3. kişiler tarafından müdahaleyi ve kullanılabilirliği arttırma yönlenlerinden, API tabanlı şirketler için bir çok avantaj sağlamaktadır.Gelişen blockchain teknolojisi ile bir çok şirket ve hizmetin blockchain sistemine adapte olması veya kendi blockchain sistemlerini kurmaları bir çok yönden zahmetli bir işlemdir. Chainlink sistemi bu noktada, bu blockchain dışı sistemlerin akıllı sözleşmeler ile blockchain sistemlerine adapte olmasını sağlamaktadır.\n\n"
        "\tChainlink (LINK) Madenciliği Nasıl Yapılır?\n\n"
        "\tChainlink madenciliği yapılmayan bir kripto para türüdür. Tüm Chainlink miktarı şirket tarafından üretilmektedir. Chainlink (LINK) toplamda 1.000.000.000 (1 milyar) adet üretilecektir. Şu anda piyasada bulunan Chainlink (LINK) adedi 350.000.000’dur.\n\n",
    "\t Neo Tarihçesi Ve Özellikleri\n\n"
        "\t NEO -orijinal adıyla “AntShares”- Da Hongfei tarafından 2014 yılında icat edildi. NEO’nın AntShares’ten NEO ismine geçişi de Haziran 2017 tarihinde olmuştur.NEO, Çin’in ilk dijital para birimiydi ve Ethereum ile direkt olarak rekabet içindeydi. Ethereum gibi, NEO da bir dijital para biriminden çok daha fazlası. NEO’nun fiyat tahminleri konusunda en çok ekisi olan da bu.NEO temel olarak blockchain temelli bir platformdur. Geliştiricilerin akıllı kontratlar ve merkezi olmayan başvurular oluşturmalarına imkan verir. Akıllı kontratlar geleceğin modası ve çoğu gerçek hayattaki duruma ve işletmeye uygulanabilirler.Aslında Ethereum bu akıllı kontratların ilk yapımcısıydı. Bu yüzden NEO çoğu zaman “Çin Ethereum’u” diye anılır. NEO coin yorum bu açıdan Ethereum'la birlikte değerlendirilmelidir.Not: Akıllı kontratlar, bazı -önceden hazırlanmış- koşullar yerine geldiği zaman kendilerini otomatik olarak çalıştıracak olan kontratlardır. Yani herhangi bir üçüncü partinin işin içine girmesine gerek yoktur.Bitcoin’le karşılaştırıldığı zaman, NEO’nun bundan çok daha farklı olduğunu görebilirsiniz. Bunun sebebi de Bitcoin’in tek amacının bir dijital para birimi olmasıdır. Bir tür USD, CAD, GRP vs.ye alternatif olması gibi.Daha önce bahsettiğim gibi, NEO’nun sıradan bir dijital para birimi olmak dışında çok farklı kullanım alanı var.NEO’nun bazı anahtar özellikleri:Çoğu kripto paranın aksine, NEO coin bölünemez. Yani mesela 0.5 NEO ya da 0.11 NEO ile bir işlem yapamazsınız. NEO bir şirketin hisseleri gibi düşünülebilir, ancak bölünemez.NEO topluluğu tarafından kullanılan ikinci bir kripto para birimi daha var: GAS. Cüzdanınızda NEO coin’i bulundurarak GAS kazanıyorsunuz ve bu da NEO’nun blockchain’i üzerinde işlem yapmanızı sağlıyor.GAS 0.00000001 ile bölünebildiği için, GAS tokenları işlem ücretleri ödemelerinde kullanılıyor. Bunlar da ağ üzerindeki uygulamalar tarafından oluşturuluyor. Aynı Ether’in Ethereum ağı üzerinde kullanılması gibi, GAS da NEO ağında kullanılıyor.Ethereum programcıların tek bir kod ile kodlamasına izin verirlen (Solidity), Neo geliştiricilere C++, C#, Go, Java gibi diller kullanarak akıllı kontratlar yazmalarına izin veriyor. Diğer bilinen programlama dillerine de izin veriyor.\n\n",
    "\tStellar Tarihçesi Ve Özellikleri\n\n"
        "\tStellar (XLM) 2014 yılında Joyce ve Jed McCaleb tarafından kurulmuştur ve varlık transferlerine bir alternatif olarak ortaya çıkmıştır. Stellar’ın çıkışından 1 sene sonra sistemin kripto para birimi olan Lumens piyasaya sürülmüştür.Stellar (XLM), dağınık ve açık kodlu bir ödeme sistemidir. Temel amacı bankalar arası uluslararası varlık transferlerini sağlamaktır. Uluslararası varlık transferleri bankalar üzerinden yapıldığında hem süre hem de masraf açısından kullanışsız olmaktadır. Stellar (XLM) ile amaç bu varlık transferlerini hızlı ve düşük ücretlere yapmaktır.Stellar (XLM) bu transferleri merkeziyetsiz sunucular ve dağınık defter teknolojisi ile yapmaktadır. Bitcoin ve Ethereum sistemlerine göre çok daha hızlı transfer edilmektedir.Stellar her ne kadar varlık transferi amacı ile ortaya çıkmış olsa da, çok katmanlı Stellar sisteminde akıllı sözleşmeler yaratmak ve yürütmek imkanı da vardır. Bu imkan sayesinde Stellar ağı üzerinde yeni tokenler üretilebilir ve transferi yapılabilmektedir.\n\n"
        "\tRipple (XRP) ile Stellar (XLM) Arasındaki Fark Nedir?\n\n"
        "\t Stellar ve Ripple sistemlerinin her ikisi de varlık transferlerinin hızlı ve ucuz gerçekleştirilmesi amacıyla yola çıkmıştır.Ripple 2012 yılında piyasaya çıktığında amacı büyük para transferi şirketlerine rakip olmaktı. Reel para transfer araçlarına alternatif olmayı amaçlıyordu. Stellar kurucularından McCaleb’in Ripple yönetimi ile yaşadığı sorunlar sonrasında şirketten ayrılarak Stellar’ı kurdu.\n\n"
        "\t 1.Ripple, Stellar’a göre daha merkeziyetli bir yapıya sahiptir. Tüm Ripple işlemleri ve bakiyesi şirketin bünyesinde ve piyasaya sürdükleridir.\n\n"
        "\t 2.Ripple büyük bankalar, borsalar ve ödeme şirketleri ile iş ortaklığı kurmayı amaçlarken, Stellar bankacılık hizmetlerine ulaşamayan insanlara bu hizmeti getirmeyi amaçlar.\n\n"
        "\t 3.Ripple kar amacı güden bir politikaya sahipken, Stellar kar amacı olmayan bir vakıf olarak işlemlere devam etmektedir.\n\n",
    "\tTron(TRX) Tarihçesi Ve Özellikleri\n\n"
        "\t Tron (TRX), Justin Sun tarafından piyasaya çıkarılmıştır ve CEO görevini halen kendisi yapmaktadır. Singapur çıkışlı Tron, merkeziyetsiz bir yapıya sahip kripto para birimidir.Tron eğlence sektörünü hedefleyen bir kripto para sistemidir. Tron üzerinden üretilen içeriklerin insanlara özgürce sunulması amaçlanmaktadır. Tron bu hedefine ulaşabilirse, tüm dünyada içerik üreticileri Tron üzerinden içeriğini paylaşabilecek, saklayabilecek ve üretebilecektir.Tron eğlence sektöründe var olan büyük merkezi yönetime bağlı içerik paylaşım sitelerine karşı bir duruş sergilemektedir. İçerik üreticilerinin özgür ve kesintisiz ödeme alabilmelerini amaçlar.\n\n"
        "\t Tron’un (TRX) Avantajı Nedir?\n\n"
        "\t İçerik üreticileri Tron altyapısını kullanarak, içeriklerini insanlara Tron sisteminin kripto para birimi olan TRX karşılığı satabilecekler. Tron bu ekosistemi inşa edebilirse hem kullanıcı hem de içerik üreticilerini büyük bir masraftan kurtaracaktır.Tron platformunda paylaşılan bir içerikten, içerik üreticisi hem kullanıcılardan TRX ile bağış alabilir, izlenme ve beğeni sayısına göre TRX kazanabilir. Tüm kazanımlardan Tron hiçbir ücret kesintisi yapmamaktadır.Tron platformunun içerik üreticilerine verdiği bazı garantiler de mevcuttur. Tron platformuna yüklenen her içerik tüm çalınma veya kopyalanma riskine karşı tüm güvenliği sağlayacağını belirtmektedir.Tron platformu içerisinde bulunan içeriklerin alım ve satımlarının güvenirliği Tron tarafından sağlanmakta ve dolandırılmaların önüne geçilmektedir.\n\n"
        "\t  Tron (TRX) Madenciliği Nasıl Yapılır?\n\n"
        "\t Tron (TRX), madenciliği yapılabilen bir kripto para birimidir. Genel madencilik mantığı ile yapılmaktadır. Madencilik için özel cihazlara gerek duyulmaktadır. Madenciler Tron ağı üzerinde yapılan işlemleri kayıt altına almaktadırlar, kayıt altına aldıkları işlem karşılığında ödül olarak TRX almaktadırlar.Tron (TRX) madencilik ile üretilen bir kripto para olduğu için arz uzun bir zamana dağıtılmış şekildedir. Şu ana kadar yaklaşık 72 milyon TRX piyasada bulunmaktadır, toplam arz ise 100 milyon TRX’in üstünde olacaktır.\n\n",
    "\tBitTorrent Token Tarihçesi Ve Özellikleri\n\n"
        "\t2001 yılında faaliyete geçen eşler arası dosya paylaşım protokolü BitTorrent ile bütünleşik biçimde çalışan BTT, daha hızlı dosya aktarımı için kullanılabiliyor. Eşler arası ağda paylaşılan dosyaların indirme hızını artırmak için kullanılabilen BTT aynı zamanda, indirilmiş dosyaların diğer kullanıcılara paylaşılması (seed) karşılığında da kazanılabiliyor.Daha basit bir ifadeyle kullanıcılar, BTT ödeyerek dosyaları daha hızlı indirebiliyor, indirme işlemi bittikten sonra bu dosyayı paylaşıma açarak BTT kazanabiliyor.\n\n"
        "\t Brad Cohen ve David Harrison tarafından geliştirilen BitTorrent, 2004 yılında şirket haline geldi. 2018 yılında ise kripto para ekosisteminin tanıdık simalarından Justin Sun'ın sahibi olduğu Tron şirketi tarafından satın alındı.\n\n"
        "\tBTT BİTTORRENT TOKEN HAKKINDA BAZI BİLGİLER\n\n"
        "\t 1.BTT’nin ilk büyük uygulaması, BitTorrent’teki dosya paylaşım sürecini kullanıcılar için daha verimli hale getirmek..\n\n"
        "\t 2.BitTorrent’te bir dosya paylaşmak, her biri belirli bir dosyanın küçük parçalarını birbirinden indiren birkaç farklı peers yani eşler içerir. Dosyanın tam kopyası olan kullanıcılar ise seeds yani tohum olarak adlandırılır.\n\n"
        "\t 3.Orijinal geliştirici Bram Cohen'in internet kullanıcılarının direkt olarak kendi aralarında içerik dağıtmasının faydalarını görmesiyle pahalı ve verimsiz dağıtım ağlarının ortadan kaldırılması hedeflendi.\n\n"
        "\t 4.2000'lerin başlarında BitTorrent ilk başvurulacak P2P dosya paylaşım platformu haline geldi ve ardından 2018'de TRON devreye girdi.\n\n"
        "\t 5.TRON'un altında BitTorrent, kendi kullanıcı tabanına ek olarak merkeziyetsiz çözümler sunarak kullanıcılar açısından cazibesini artırdı ve kripto para alanındaki kullanıcılara da ulaştı.\n\n"
        "\t 6.Eklenen özelliklerin arasında, işlemlerin bir parçası olarak BTT tokeninin kullanıldığı BitTorrent Speed seçeneği var.lBitTorrent, platformunun, VPN özellikleri ve reklamsız aramanın dahil olduğu birkaç Premium sürümü sunarak ücretli hizmetler alanına da girdi.\n\n",
  ];
}
